name: Firebase Backup

on:
  repository_dispatch:
    types: [backup]   # 👈 admin panel se trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Firebase JSON
        run: |
          mkdir -p backups
          curl -o backups/temp.json "https://opjat-2005-default-rtdb.asia-southeast1.firebasedatabase.app/.json"

      - name: Rename file with time
        run: |
          mv backups/temp.json backups/backup_$(date +%Y-%m-%d_%H-%M-%S).json

      - name: Commit & Push
        run: |
          git config user.name "backup-bot"
          git config user.email "backup@bot.com"
          git add backups/
          git commit -m "Auto backup $(date)" || echo "No changes"
          git push